COMPILER = g++
CFLAGS = -O3 -std=c++11 -static -lpthread
# -fsanitize=address -fsanitize=leak -O3 

PRE_CFLAGS = ${CFLAGS} -c
TARGET = LS-Sampling-Plus

SRC_DIR = src

LIB_DIR = lib

BIN_DIR = bin

CADICAL = cadical

MERSENNE = mersenne
MERSENNE_TARGET = ${SRC_DIR}/${MERSENNE}.o
MERSENNE_CC_FILE = ${SRC_DIR}/${MERSENNE}.cc
MERSENNE_H_FILE = ${SRC_DIR}/${MERSENNE}.h
MERSENNE_SOURCE_FILES = ${MERSENNE_H_FILE} ${MERSENNE_CC_FILE}

PBOCCSATSOLVER = pboccsatsolver
PBOCCSATSOLVER_TARGET = ${SRC_DIR}/${PBOCCSATSOLVER}.o
PBOCCSATSOLVER_CPP_FILE = ${SRC_DIR}/${PBOCCSATSOLVER}.cpp
PBOCCSATSOLVER_H_FILE = ${SRC_DIR}/${PBOCCSATSOLVER}.h
PBOCCSATSOLVER_SOURCE_FILES = ${SOLVER_H_FILE} ${SOLVER_CPP_FILE}

SLSTESTCASESAMPLER = slstestcasesampler
SLSTESTCASESAMPLER_TARGET = ${SRC_DIR}/${SLSTESTCASESAMPLER}.o
SLSTESTCASESAMPLER_CPP_FILE = ${SRC_DIR}/${SLSTESTCASESAMPLER}.cpp
SLSTESTCASESAMPLER_H_FILE = ${SRC_DIR}/${SLSTESTCASESAMPLER}.h
SLSTESTCASESAMPLER_SOURCE_FILES = ${SLSTESTCASESAMPLER_H_FILE} ${SLSTESTCASESAMPLER_CPP_FILE}

EXT_MINISAT_TARGET = minisat_ext/MapleSATSolver.o minisat_ext/Ext.o
EXT_MINISAT_SOURCE_FILES = minisat_ext/MapleSATSolver.cc minisat_ext/MapleSATSolver.h minisat_ext/Ext.h minisat_ext/Ext.cc

TARGET_FILES =	${EXT_MINISAT_TARGET} \
				${MERSENNE_TARGET} \
				${PBOCCSATSOLVER_TARGET} \
				${SLSTESTCASESAMPLER_TARGET} \
				
MAIN_SOURCE_FILE = ${SRC_DIR}/main.cpp


UPDATE = update
CLEAN = clean
CLEANUP = cleanup


all: ${TARGET_FILES} ${TARGET} ${UPDATE} ${CLEAN}

${MERSENNE_TARGET}: ${MERSENNE_SOURCE_FILES}
	${COMPILER} ${PRE_CFLAGS} ${MERSENNE_CC_FILE} -o ${MERSENNE_TARGET}

${PBOCCSATSOLVER_TARGET}: ${PBOCCSATSOLVER_SOURCE_FILES}
	${COMPILER} ${PRE_CFLAGS} ${PBOCCSATSOLVER_CPP_FILE} -o ${PBOCCSATSOLVER_TARGET}

${SLSTESTCASESAMPLER_TARGET}: ${SLSTESTCASESAMPLER_SOURCE_FILES}
	${COMPILER} ${PRE_CFLAGS} ${SLSTESTCASESAMPLER_CPP_FILE} -o ${SLSTESTCASESAMPLER_TARGET} -L ${LIB_DIR} -l${CADICAL}


${EXT_MINISAT_TARGET}: ${EXT_MINISAT_SOURCE_FILES}
	cd minisat_ext; make -f Makefile extminisat; cd ..

${TARGET}: ${MAIN_SOURCE_FILE} ${TARGET_FILES}
	${COMPILER} ${CFLAGS} ${MAIN_SOURCE_FILE} ${TARGET_FILES} -o ${TARGET} -L ${LIB_DIR} -l${CADICAL} -lpthread

${UPDATE}:
	chmod +x ${BIN_DIR}/*

${CLEAN}:
	rm -f *~
	rm -f ${SRC_DIR}/*.o
	rm -f ${SRC_DIR}/*~
	rm -f ${EXT_MINISAT_TARGET}

${CLEANUP}: ${CLEAN}
	rm -f ${TARGET}
